//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyFitNative.Infrastructure.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DailyFitNative.Infrastructure.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string msgEmptyMail {
            get {
                return ResourceManager.GetString("msgEmptyMail", resourceCulture);
            }
        }
        
        public static string msgEmptyPassword {
            get {
                return ResourceManager.GetString("msgEmptyPassword", resourceCulture);
            }
        }
        
        public static string msgInvalidEmail {
            get {
                return ResourceManager.GetString("msgInvalidEmail", resourceCulture);
            }
        }
        
        public static string txtAppName {
            get {
                return ResourceManager.GetString("txtAppName", resourceCulture);
            }
        }
        
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        public static string txtForgotPassword {
            get {
                return ResourceManager.GetString("txtForgotPassword", resourceCulture);
            }
        }
        
        public static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        public static string txtSignIn {
            get {
                return ResourceManager.GetString("txtSignIn", resourceCulture);
            }
        }
        
        public static string txtNotHaveAccount {
            get {
                return ResourceManager.GetString("txtNotHaveAccount", resourceCulture);
            }
        }
        
        public static string txtSignUp {
            get {
                return ResourceManager.GetString("txtSignUp", resourceCulture);
            }
        }
        
        public static string txtConfirmPassword {
            get {
                return ResourceManager.GetString("txtConfirmPassword", resourceCulture);
            }
        }
        
        public static string txtHaveAccount {
            get {
                return ResourceManager.GetString("txtHaveAccount", resourceCulture);
            }
        }
        
        public static string txtRegister {
            get {
                return ResourceManager.GetString("txtRegister", resourceCulture);
            }
        }
        
        public static string txtYourEmail {
            get {
                return ResourceManager.GetString("txtYourEmail", resourceCulture);
            }
        }
        
        public static string msgEmptyConfirmPassword {
            get {
                return ResourceManager.GetString("msgEmptyConfirmPassword", resourceCulture);
            }
        }
    }
}
